import { Fragment } from "react";

import { Metadata } from "next";

import Header from "@/components/layouts/Header";
import "@/styles/globals.scss";

export const metadata: Metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <Fragment>
      <Header />
      <main>{children}</main>
    </Fragment>
  );
}
