import { Metadata } from "next";

import Footer from "@/components/layouts/Footer";
import Header from "@/components/layouts/Header";
import "@/styles/globals.scss";

export const metadata: Metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Header />
        <main>{children}</main>
      </body>
    </html>
  );
}
