import clsx from "clsx";
import { Metadata } from "next";

import "@/styles/globals.scss";

export const metadata: Metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={clsx(`font-sans`)}>
        <main>{children}</main>
      </body>
    </html>
  );
}
