import { Fragment } from "react";

import clsx from "clsx";
import { Metadata } from "next";

export const metadata: Metadata = {
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <Fragment>
      <main className={clsx([`sm:p-0`])}>{children}</main>
    </Fragment>
  );
}
