import clsx from "clsx";
import { Metadata } from "next";

export const metadata: Metadata = {
  description: "Generated by Next.js",
};

export default function OfficerIndexLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <div
      className={clsx([
        `from-dark-green-500 absolute bg-gradient-to-r to-black`,
        `w-full md:h-screen`,
      ])}
    >
      {children}
    </div>
  );
}
